version: '3.8'  # Use a versão do Compose compatível com o Docker Engine instalado

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres  # Usar o volume chamado "db"
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped  # Correção na escrita da opção "unless-stopped"

networks:
  db:
    driver: bridge

volumes:
  db:  # Definir o volume "db"
